apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.7/manifests/install.yaml
- argocd-server-ingress.yml
patches:
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cmd-params-cm
    patch: |-
      - op: add
        path: /data
        value: {"server.insecure": "{{ argocd_server_insecure }}"}
