---
- name: Remove an existing Cluster object
  kubernetes.core.k8s:
    state: absent
    api_version: v1beta1
    kind: Cluster
    namespace: "{{ capi_management_workload_cluster_namespace }}" 
    name: "{{ capi_cluster_name }}"
