#!/usr/bin/env ansible-playbook
---
- name: Delete an Openstack proxy machine
  hosts: localhost
  vars:
    machine_name: "{{ proxy_machine_name | default('proxy-machine', true) }}"
  roles:
  - delete_machine_openstack
