- name: Create security group
  openstack.cloud.security_group:
    cloud: "{{ openstack_cloud }}"
    state: present
    name: "{{ security_group_name }}"
    description: security group for {{ proxy_machine_name }}

- name: Create security group rules
  openstack.cloud.security_group_rule:
    cloud: "{{ openstack_cloud }}"
    security_group: "{{ security_group_name }}"
    protocol: tcp
    port_range_min: "{{ item }}"
    port_range_max: "{{ item }}"
    remote_ip_prefix: 0.0.0.0/0
  loop: "{{ security_group_ports }}"
